export const INDUSTRY_FIELDS = [
  "Agriculture",
  "Automobiles",
  "Fabricators",
  "Mining industries",
  "Transport",
  "Engineering & EPC",
  "Food processing",
  "Construction",
  "Manufacturing industries",
  "Power & Energy",
  "Railways",
  "EOT crane & Elevators",
  "Precast products",
  "Heavy machinery manufacturer",
  "Staircase Fabricators",
  "Shed & PEB Fabricators",
  "Bus body",
  "Quarry plant",
  "Facade work",
  "Kolawala",
  "Material handling equipment",
  "Petrolpump contractors",
  "Semi ghanti",
  "Textile machine manufacturers",
  "Truck tipper",
  "Steel traders"
];
